// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  call_to_action: dynamic(() => import("./CallToAction")),
  card_grid: dynamic(() => import("./CardGrid")),
  faq: dynamic(() => import("./Faq")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  hightlighted_text: dynamic(() => import("./HightlightedText")),
  image: dynamic(() => import("./Image")),
  image_beside_text: dynamic(() => import("./ImageBesideText")),
  image_slider: dynamic(() => import("./ImageSlider")),
  job_list: dynamic(() => import("./JobList")),
  map: dynamic(() => import("./Map")),
  navigation_slice: dynamic(() => import("./NavigationSlice")),
  pricing: dynamic(() => import("./Pricing")),
  search: dynamic(() => import("./Search")),
  team: dynamic(() => import("./Team")),
  text: dynamic(() => import("./Text")),
  text_grid_row: dynamic(() => import("./TextGridRow")),
  ticket_pointing: dynamic(() => import("./TicketPointing")),
  video: dynamic(() => import("./Video")),
};
